{
  config,
  lib,
  pkgs,
  utils,
  ...
}:
let
  cfg = config.services.rtp2httpd;
  inherit (lib) mkIf mkOption types;

  singleLine = types.addCheck types.str (
    value: !(lib.hasInfix "\n" value || lib.hasInfix "\r" value)
  );
  globalType = types.attrsOf (
    types.oneOf [
      types.bool
      types.int
      singleLine
    ]
  );
  bindLine = types.strMatching "(/[^[:space:]]+|[^[:space:]]+[ \t]+[^[:space:]]+)";
  bind = if cfg.settings.bind == null then [ "* 5140" ] else cfg.settings.bind;
  # The Nix option is named loglevel; the upstream parser expects verbosity.
  globalSettings =
    builtins.removeAttrs cfg.settings.global [ "loglevel" ]
    // lib.optionalAttrs (cfg.settings.global ? loglevel) {
      verbosity = cfg.settings.global.loglevel;
    };

  # Only [global] is a key/value section. [bind] contains bare address lines,
  # and [services] contains M3U metadata whose '#' prefixes must be preserved.
  configText = ''
    [global]
    ${lib.generators.toKeyValue { } globalSettings}
    [bind]
    ${lib.concatStringsSep "\n" bind}

    [services]
    ${cfg.settings.services}
  '';
  generatedConfig = pkgs.writeText "rtp2httpd.conf" configText;
  configPath = "/etc/rtp2httpd.conf";

  integerRanges = {
    loglevel = {
      min = 0;
      max = 4;
    };
    maxclients = {
      min = 1;
      max = 256;
    };
    workers = {
      min = 1;
      max = 32;
    };
    buffer-pool-max-size = {
      min = 1;
      max = 2147483647;
    };
    udp-rcvbuf-size = {
      min = 65536;
      max = 2147483647;
    };
    mcast-rejoin-interval = {
      min = 0;
      max = 2147483647;
    };
    external-m3u-update-interval = {
      min = 0;
      max = 2147483647;
    };
  };
  booleanKeys = [
    "udpxy"
    "xff"
    "video-snapshot"
    "use-relative-path-in-m3u"
  ];
  firstServiceLine = lib.findFirst (line: lib.trim line != "") "" (
    lib.splitString "\n" cfg.settings.services
  );
in
{
  options.services.rtp2httpd = {
    enable = lib.mkEnableOption "the rtp2httpd IPTV streaming server";
    package = lib.mkPackageOption pkgs "rtp2httpd" { };

    settings = mkOption {
      default = { };
      description = ''
        Declarative rtp2httpd configuration, generated by Nix and stored in
        the Nix store.
        See <https://rtp2httpd.com/reference/configuration>.
      '';
      type = types.submodule {
        options = {
          global = mkOption {
            type = globalType;
            default = { };
            example = {
              loglevel = 3;
              maxclients = 20;
              upstream-interface = "iptv";
            };
            description = ''
              Options in [global], using upstream's hyphenated names except
              loglevel, which is written as verbosity: 0 = FATAL, 1 = ERROR,
              2 = WARN, 3 = INFO, 4 = DEBUG (upstream default: 1).
              Strings are written without quoting; booleans become true or false.
              Numeric and boolean options must use their corresponding Nix types.
              Omitted options retain the upstream defaults.
            '';
          };
          bind = mkOption {
            type = types.nullOr (types.nonEmptyListOf bindLine);
            default = null;
            example = [
              "192.168.1.1 5140"
              "::1 5140"
              "/run/rtp2httpd/http.sock"
            ];
            description = ''
              Lines in [bind]: an address and port separated by whitespace,
              or an absolute Unix socket path without whitespace. Null uses
              the upstream default, [ "* 5140" ]. An empty list is not allowed.
              Firewall rules must be configured separately on the host.
            '';
          };
          services = mkOption {
            type = types.lines;
            default = "";
            example = ''
              #EXTM3U
              #EXTINF:-1,CCTV-1
              rtp://239.253.64.120:5140
            '';
            description = ''
              Inline M3U content for [services], beginning with #EXTM3U when
              nonempty. It can be combined with global.external-m3u.
            '';
          };
        };
      };
    };
  };

  config = mkIf cfg.enable {
    assertions = [
      {
        assertion = !(cfg.settings.global ? verbosity);
        message = "Use services.rtp2httpd.settings.global.loglevel instead of verbosity.";
      }
      {
        assertion = lib.all (name: builtins.match "[A-Za-z][A-Za-z0-9_-]*" name != null) (
          builtins.attrNames cfg.settings.global
        );
        message = "services.rtp2httpd.settings.global contains an invalid option name.";
      }
      {
        # fgets reads at most 4095 bytes, including the terminating newline.
        assertion = lib.all (line: builtins.stringLength line <= 4094) (lib.splitString "\n" configText);
        message = "services.rtp2httpd.settings contains a line longer than 4094 bytes.";
      }
      {
        assertion = firstServiceLine == "" || lib.hasPrefix "#EXTM3U" (lib.trim firstServiceLine);
        message = "services.rtp2httpd.settings.services must begin with #EXTM3U when nonempty.";
      }
    ]
    ++ lib.mapAttrsToList (name: range: {
      assertion =
        !(cfg.settings.global ? ${name})
        || (
          builtins.isInt cfg.settings.global.${name}
          && cfg.settings.global.${name} >= range.min
          && cfg.settings.global.${name} <= range.max
        );
      message = "services.rtp2httpd.settings.global.${name} must be an integer between ${toString range.min} and ${toString range.max}.";
    }) integerRanges
    ++ map (name: {
      assertion = !(cfg.settings.global ? ${name}) || builtins.isBool cfg.settings.global.${name};
      message = "services.rtp2httpd.settings.global.${name} must be a boolean.";
    }) booleanKeys;

    environment.systemPackages = [ cfg.package ];
    environment.etc."rtp2httpd.conf" = {
      source = generatedConfig;
    };

    systemd.services.rtp2httpd = {
      description = "rtp2httpd IPTV streaming server";
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];
      wantedBy = [ "multi-user.target" ];
      # Keep ExecStart's path stable, so SIGHUP reads the newly activated file.
      reloadTriggers = [ generatedConfig ];
      serviceConfig = {
        Type = "simple";
        ExecStartPre = utils.escapeSystemdExecArgs [
          "${pkgs.coreutils}/bin/test"
          "-r"
          configPath
        ];
        ExecStart = utils.escapeSystemdExecArgs [
          (lib.getExe cfg.package)
          "--config"
          configPath
        ];
        ExecReload = "${pkgs.coreutils}/bin/kill -HUP $MAINPID";
        Restart = "on-failure";
        RestartSec = 3;
        DynamicUser = true;
        UMask = "0027";
        RuntimeDirectory = "rtp2httpd";
        RuntimeDirectoryMode = "0750";
        LogsDirectory = "rtp2httpd";
        LogsDirectoryMode = "0750";
        # NET_ADMIN allows SO_RCVBUFFORCE; NET_RAW allows raw IGMP rejoin.
        # Add NET_BIND_SERVICE explicitly when using privileged listen ports.
        AmbientCapabilities = [
          "CAP_NET_ADMIN"
          "CAP_NET_RAW"
        ];
        CapabilityBoundingSet = [
          "CAP_NET_ADMIN"
          "CAP_NET_RAW"
        ];
        NoNewPrivileges = true;
        PrivateTmp = true;
        ProtectHome = true;
        ProtectSystem = "strict";
        ProtectKernelTunables = true;
        ProtectKernelModules = true;
        ProtectControlGroups = true;
        RestrictSUIDSGID = true;
      };
    };
  };
}
