# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aws-lc = {
    pname = "aws-lc";
    version = "v1.58.1";
    src = fetchFromGitHub {
      owner = "aws";
      repo = "aws-lc";
      rev = "v1.58.1";
      fetchSubmodules = false;
      sha256 = "sha256-g8UFXixWO7PAjiHaMQsHh3OmaoZcqKt6JPVjhlzfXqM=";
    };
  };
  fcitx5-pinyin-zhwiki = {
    pname = "fcitx5-pinyin-zhwiki";
    version = "20250823";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.5/zhwiki-20250823.dict";
      sha256 = "sha256-cD0FKxPvdQfcrfR/Fh4aNb+pK/IFiFLyvg8LhnYI+vs=";
    };
  };
  nvidia_gpu_exporter = {
    pname = "nvidia_gpu_exporter";
    version = "v1.3.2";
    src = fetchFromGitHub {
      owner = "utkuozdemir";
      repo = "nvidia_gpu_exporter";
      rev = "v1.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-d5/sWgfb4rGfHHeHOunHkm61F6o9L/z0MLh7iRABEYg=";
    };
  };
  qbittorrent-enhanced-nox = {
    pname = "qbittorrent-enhanced-nox";
    version = "release-5.1.2.10";
    src = fetchFromGitHub {
      owner = "c0re100";
      repo = "qBittorrent-Enhanced-Edition";
      rev = "release-5.1.2.10";
      fetchSubmodules = false;
      sha256 = "sha256-Q3gipRgZCzihKUQZZmETT65AUSEUfgj9dFxZFybq258=";
    };
  };
  rabbit-digger-pro = {
    pname = "rabbit-digger-pro";
    version = "c356f58eaa82c6770de5402fcff1726938a02cde";
    src = fetchgit {
      url = "https://github.com/rabbit-digger/rabbit-digger-pro";
      rev = "c356f58eaa82c6770de5402fcff1726938a02cde";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-BBscXZetO1mIvIzap6F6ArdaaeqeFhwNGWHqqykVcEs=";
    };
    "Cargo.lock" = builtins.readFile ./rabbit-digger-pro-c356f58eaa82c6770de5402fcff1726938a02cde/Cargo.lock;
    date = "2025-08-09";
  };
  smartdns-china-list = {
    pname = "smartdns-china-list";
    version = "36753c08b02f58a7b7d8cbdd12540a5402ff3f15";
    src = fetchFromGitHub {
      owner = "felixonmars";
      repo = "dnsmasq-china-list";
      rev = "36753c08b02f58a7b7d8cbdd12540a5402ff3f15";
      fetchSubmodules = false;
      sha256 = "sha256-3J3gC9dJFJqgkEj6zOLIUXmXzDpZjg5u0WNZjJEUz8A=";
    };
    date = "2025-08-06";
  };
  vscode-ext-ccls = {
    pname = "vscode-ext-ccls";
    version = "0.1.32";
    src = fetchurl {
      url = "https://ccls-project.gallery.vsassets.io/_apis/public/gallery/publisher/ccls-project/extension/ccls/0.1.32/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ccls-0.1.32.zip";
      sha256 = "sha256-sCsRwS2z/jJpHeSuSdcitk39WEzKBiaZgt0gYRpViYU=";
    };
    publisher = "ccls-project";
    name = "ccls";
  };
  vscode-ext-codeium = {
    pname = "vscode-ext-codeium";
    version = "1.49.2";
    src = fetchurl {
      url = "https://Codeium.gallery.vsassets.io/_apis/public/gallery/publisher/Codeium/extension/codeium/1.49.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "codeium-1.49.2.zip";
      sha256 = "sha256-fLDR0Gb8J9DkKTwFm0oMHB1GENKH/Cj2jMb1AsP0ZpQ=";
    };
    publisher = "Codeium";
    name = "codeium";
  };
  vscode-ext-sops = {
    pname = "vscode-ext-sops";
    version = "0.9.2";
    src = fetchurl {
      url = "https://signageos.gallery.vsassets.io/_apis/public/gallery/publisher/signageos/extension/signageos-vscode-sops/0.9.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "signageos-vscode-sops-0.9.2.zip";
      sha256 = "sha256-qlFD8sMvdKpLkXiYT9UybgCvxUJrbXpAcnmPxk91Tbs=";
    };
    publisher = "signageos";
    name = "signageos-vscode-sops";
  };
  xdg-open-server = {
    pname = "xdg-open-server";
    version = "v1.3";
    src = fetchFromGitHub {
      owner = "kitsunyan";
      repo = "xdg-open-server";
      rev = "v1.3";
      fetchSubmodules = false;
      sha256 = "sha256-BX/Z3e1MQMISWWtrw+D1ChwdIhwxgWOx2evgZdMkPjg=";
    };
  };
  yarr-pgsql = {
    pname = "yarr-pgsql";
    version = "v3.1.6";
    src = fetchFromGitHub {
      owner = "jgkawell";
      repo = "yarr";
      rev = "v3.1.6";
      fetchSubmodules = false;
      sha256 = "sha256-RO3kZFpryKmYDlQBDOK/6ujcCuT/F2rg7TyV25Y4PgY=";
    };
  };
}
