# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  fcitx5-pinyin-zhwiki = {
    pname = "fcitx5-pinyin-zhwiki";
    version = "20250823";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.5/zhwiki-20250823.dict";
      sha256 = "sha256-cD0FKxPvdQfcrfR/Fh4aNb+pK/IFiFLyvg8LhnYI+vs=";
    };
  };
  nvidia_gpu_exporter = {
    pname = "nvidia_gpu_exporter";
    version = "v1.4.1";
    src = fetchFromGitHub {
      owner = "utkuozdemir";
      repo = "nvidia_gpu_exporter";
      rev = "v1.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-+sXlQQUs8tmxtaqKUCBTfEZlL8fqBlhzcDFbX8Catsk=";
    };
  };
  smartdns-china-list = {
    pname = "smartdns-china-list";
    version = "b524f7faa31c43359eab372c80870581508124a1";
    src = fetchFromGitHub {
      owner = "felixonmars";
      repo = "dnsmasq-china-list";
      rev = "b524f7faa31c43359eab372c80870581508124a1";
      fetchSubmodules = false;
      sha256 = "sha256-31uV1m2m4ExbiIwsXfIzH35mgidn0QAuTdAWA7m+EJY=";
    };
    date = "2025-10-26";
  };
  vscode-ext-ccls = {
    pname = "vscode-ext-ccls";
    version = "0.1.32";
    src = fetchurl {
      url = "https://ccls-project.gallery.vsassets.io/_apis/public/gallery/publisher/ccls-project/extension/ccls/0.1.32/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ccls-0.1.32.zip";
      sha256 = "sha256-sCsRwS2z/jJpHeSuSdcitk39WEzKBiaZgt0gYRpViYU=";
    };
    publisher = "ccls-project";
    name = "ccls";
  };
  vscode-ext-codeium = {
    pname = "vscode-ext-codeium";
    version = "1.49.2";
    src = fetchurl {
      url = "https://Codeium.gallery.vsassets.io/_apis/public/gallery/publisher/Codeium/extension/codeium/1.49.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "codeium-1.49.2.zip";
      sha256 = "sha256-fLDR0Gb8J9DkKTwFm0oMHB1GENKH/Cj2jMb1AsP0ZpQ=";
    };
    publisher = "Codeium";
    name = "codeium";
  };
  vscode-ext-sops = {
    pname = "vscode-ext-sops";
    version = "0.9.3";
    src = fetchurl {
      url = "https://signageos.gallery.vsassets.io/_apis/public/gallery/publisher/signageos/extension/signageos-vscode-sops/0.9.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "signageos-vscode-sops-0.9.3.zip";
      sha256 = "sha256-fOSLlszr6yLkRC9gy+MCnL+Y/1TXrmVWAWavpvXHj4U=";
    };
    publisher = "signageos";
    name = "signageos-vscode-sops";
  };
  xdg-open-server = {
    pname = "xdg-open-server";
    version = "v1.3";
    src = fetchFromGitHub {
      owner = "kitsunyan";
      repo = "xdg-open-server";
      rev = "v1.3";
      fetchSubmodules = false;
      sha256 = "sha256-BX/Z3e1MQMISWWtrw+D1ChwdIhwxgWOx2evgZdMkPjg=";
    };
  };
  yarr-pgsql = {
    pname = "yarr-pgsql";
    version = "v3.1.6";
    src = fetchFromGitHub {
      owner = "jgkawell";
      repo = "yarr";
      rev = "v3.1.6";
      fetchSubmodules = false;
      sha256 = "sha256-RO3kZFpryKmYDlQBDOK/6ujcCuT/F2rg7TyV25Y4PgY=";
    };
  };
}
