nixtoken: ENC[AES256_GCM,data:w1xUJClbDdpGmgM1o6WHY8SMPTyMv7fHkU3UBtUdtFvv0RU8UUoh+yYsWAD4PCy0aWcnd3dqyOIvlYwOlPfE2nUcRjeRaysTUS46RyU428JDbH+LEeTInmbc7uzL/JrQEwjiURgW7b8eFHbx1McWznX6a0fnm8VN,iv:ACZsSChsyV8o5cCFZuikL/qBoI8yoyb9UOrnVR6U3HQ=,tag:G+2S3KQRBfB/Nqsk2ir/DQ==,type:str]
corp-git-config: ENC[AES256_GCM,data:7EEpkxm3oi0V08lqDBKO/ekxvLWipsU2SXUdIygko1u4q6GuWX5mgnX8PW8CjkpoH96joF7fl1RD5xTWpa/tEn9CXh+eYUXfwYg=,iv:nr/uy+uktNlbif4Gb/LiHenpauzy6uwNEUgsIYVOl20=,tag:QwqlF3mlfxYgK75zwGlcCw==,type:str]
gomod-git-config: ENC[AES256_GCM,data:A/SWvFoYmdiqkne2P4QJE08Z8ukaSjlFzAFbijo4/4x4vvBRZ2f8q8FTFVCVFGbdTPLCoybW8uJFs/yGPluIFodf2IbfSKal6P/I9OZ9Zh8FVcTB123iFw9xwxkacdDPlsehW50ey3OS+LExqVkMXuw5TsP8fdLrD7dUkdmAm0MEGMeN7O3z9U77qhUvyXgKtzn8vTk7Z+XRRsB3sCvW0UPUSNFDTOWCO2ZQqUhZ0w==,iv:Ix3FYz1XJ92NiQyScigChlNMCEczVrINvj6YlzlNIis=,tag:OW+PbOlW1TeYcqoVUBm8bA==,type:str]
corp-ssh-config: ENC[AES256_GCM,data:mwRmCA7plF6hgBk5bifj3Xub39FDoySfKeHPC2I5MdfmHCHLISrpHV/8pBQ1dBQ0IcZllfuBFjhYJeKRV08k8gcZjzIHRYw5mSVa5dhMIu1QYQG9oKM8EhSXLQfuvVEARHHUMbUs7oEeZstFDqTaxq6yt32OIVhFcFiKqckkoUBClYnb6mw15UwOLmjKl1VFfQ8XkCJVYxIv+VUDMt4Z9p8DMa/1mCU8JgCkOoPj4oG5hW4M0t0z46CcnWSjjKOpg38yPlMtbcoKZCP8MeE/df9EORKFEZ4DX1EFYXs8tqPuwt5FGqblmvD1v7YRdq6zoZjZH0FDMx3n6CdrGBj5veB7hcGUcFoLhSi5l2KvU3JT4yZz2Ib8R2lS64uccaMI0Hibfb15nMvVRHPSKzfg+V/E77aSwQ+bvyB2Wcg8ePz1TjPM82iGAIVDLf+MEBxhF+L3JEz+06feWzkjQ3g1A/NKpGLR7qoonxNRZSinfiLKLtOfR+Ze+Jo5iYvMqcXpOrtodgOI7p4UTCEidycuoGhUm2ISy4+Uathuhxiq1GRkF9RCnpnsDdhpnxVFRIiOOOuWvWfvXNEyISO7H8jpwMHe0jBjS/+61bTWsX8rx9Reng5aZRcnVICsqywSJ4tw1fPf7GdjW/cXZCmNFxjEt3J72gMOMBmnNKTsMoyWLlxsJrbr/0E9YT7DzveunyIAR7BHULsvEVM=,iv:JVr72FsHZLIgynt/m4Lcjop2levq066xY8CB47AQeo8=,tag:L/+RSp9q8YzkdDftoODZsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15kt304expy6f8eemedmz529m0p0srtg07xuq6ex9ece63lns2auqd4gwvs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Y2JwR2RUdkZoUFhUUktR
            Y2Z0ZU5iRzBBL21KcFFnVW9zejNYVHZ2ZUg0Ck5DOFljN09zYWNxWEF6NlFuOGl4
            Tko1QTlwQTY0Q3pYY1c2dnN6SkJ4WEUKLS0tIFJsZ2dYV0sxTUhRNmdlUWZJdGx0
            Z3h1ZjFTOWZlTEpOUFRnc3djeFhjcEUKR7euwp3k+T7UPHspHYQY/EE38mB0Osl+
            Rf4GbfSk0ojBE+wjveEhgBjR6lddSl8hGv7LR1EPAb19umtES+8H7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T07:12:46Z"
    mac: ENC[AES256_GCM,data:ntgqJFXUeNUzZvge3GoOvX0Was6CAl1B2d0SMq/W/+w0AHlqzsjQv3m3nOHqXS94O4nOfqcdmSUITM9sZ7zGK5hcXVMnsncUfdB0R1A8fZ8VgNZ3C5Qg/i8knWF4oCGHtnFdjOGkn0uLrnK3tXECAWUvZoNeg7+mViOqMjBfonc=,iv:gF4RRn7JJxSRZ0F+pXeaguXZ2XB4ophluugsoYQVqxE=,tag:z0ixEl2MPH2C19Bao9BZDQ==,type:str]
    pgp:
        - created_at: "2022-10-12T11:35:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7XEPFWtCkpIARAAoyMuA0AFi/i2HrPA8L5Gzjnmc5I+J3zvHHbtRnYx4g+C
            kL8/3ta4Se+jvJebozDQZc1KKwzVuXsO41XhzH/TMPhOhSR3nXkLwyV0Kb+1zdbe
            zyMp30Pw7+r0oOGK+4lUlM/ZRUb1G+PADsjdcdJASQHK/+6sOYpJnRdOB3TRdihl
            odLDa057tDE/HEjoR8QOXLUNqs3nIz00ITQ/oyDPer1knfBmWIxgC09KOdmIeZ5+
            23GR+saou2aCwq7ix45XIXbjNF7jzufoYUwMBMe8d7KimTyQpLLXv6og3ExRwxIx
            5XeCk7Vzw5t4pDhKEfvd40Yi5MOqPJ7+5GLgzarKPIbqq7QRm66z9SGvPnxsguHP
            Lv+iuiMU3llqd2YxM0iKvbJyPn6gzvRV2zdII1Cuj+IOCUEzkY9Ef/MN6hxfPpqc
            2mquSsgIQuNRVFW/NvKOJC5nE8zw1/5WJh1tIUw0Ni1UdluHTHFHyoQ/FQySOp5x
            YziBrywC3M/pYG1ex42TQDiIpFOV0XVfon74rtIntp0K7OGPu2cP1dE1nWrRq6S1
            /pGSKBtXdJLJHDd3pTrzkqdbnPJ70zcJWdUjlZivZ2Qvu5IaFn//swPOPUm1WQ10
            JueEpNcEP67TAIYLv+LfvQMAiv3ToUT6OwxqJ1o7rSoWzCcebh0aMDE3HI+3HXnS
            XAG2FqM4Ti5bvTaejcJ4agoTx1irIQOAE5cGEGLPJnvkTFwsj+uRqVsjl/IiQAWF
            4YBfmwJK1yOSZdEPZ4DguwlvHpFDkFWP62Y3cD6/HpvnesOkiatC0CtOQCcv
            =HG5T
            -----END PGP MESSAGE-----
          fp: 7028E1F320C45EE98473B1C35F1BC1A1BF2B11D0
    unencrypted_suffix: _unencrypted
    version: 3.9.1
